name: My first Workflow

on: push 

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read file 
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md
        - name: Install cowsay Package
          run: sudo apt-get install cowsay -y
        - name: Generate ASCII artwork 
          run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >>dragon.txt
        - name: output cowsay 
          run: cat dragon.txt

        # - name: List files
        #   run: ls
        # - name: Read file
        #   run: cat README.md